image: Visual Studio 2019
install:
  - ps: $env:BuildNumber= $env:APPVEYOR_BUILD_NUMBER
  - ps: $env:DOTNET_SKIP_FIRST_TIME_EXPERIENCE = true
  - ps: $env:NUGET_XMLDOC_MODE = "skip"
  - ps: $env:DOTNET_CLI_TELEMETRY_OPTOUT = 1
  - ps: $IsMasterBranch = ($env:APPVEYOR_REPO_BRANCH -eq "master" -And -not $env:APPVEYOR_PULL_REQUEST_NUMBER)
  - ps: $IsDevBranch = ($env:APPVEYOR_REPO_BRANCH -eq "dev" -And -not $env:APPVEYOR_PULL_REQUEST_NUMBER)
# Uncomment to download a specific version of dotnet
  - ps: Invoke-WebRequest "https://raw.githubusercontent.com/dotnet/cli/master/scripts/obtain/dotnet-install.ps1" -OutFile "dotnet-install.ps1" 
  - ps: .\dotnet-install.ps1 --Version 3.1.300
build_script:
  - dotnet restore
  - dotnet build -c Release
  - ps: if ($IsMasterBranch -or $IsDevBranch) { dotnet pack -c Release --no-build }
init:
  - dotnet --version
  - node --version
  - npm --version
  - git config --global core.autocrlf true
artifacts:
  - path: '**\*.nupkg'
deploy:
  - provider: NuGet
    on:
      branch: master
    server: https://www.nuget.org/api/v2/package
    api_key:
      secure: owb6PTBxSlCDNSzA+XSA+N8QQEVDYenULviEFY+k4zDAQ7B/B5ZwEjc8OR50Ef8J
    skip_symbols: true
    artifact: /.*\.nupkg/  